### ISSUE TITLE
Wikipedia: SelectorParseException

### ISSUE THREAD

**Issue by mrozekma** [mrozekma/NoiseBot#72]
The link https://en.wikipedia.org/wiki/Glenda_Ritz#State_superintendent,_2012 causes:

```
Caused by: org.jsoup.select.Selector$SelectorParseException: Could not parse query '_2012': unexpected token at '_2012'
        at org.jsoup.select.QueryParser.findElements(QueryParser.java:196)
        at org.jsoup.select.QueryParser.parse(QueryParser.java:53)
        at org.jsoup.select.QueryParser.parse(QueryParser.java:39)
        at org.jsoup.select.QueryParser.combinator(QueryParser.java:81)
        at org.jsoup.select.QueryParser.parse(QueryParser.java:61)
        at org.jsoup.select.QueryParser.parse(QueryParser.java:39)
        at org.jsoup.select.Selector.<init>(Selector.java:80)
        at org.jsoup.select.Selector.select(Selector.java:93)
        at org.jsoup.nodes.Element.select(Element.java:252)
        at modules.Wikipedia.getBody(Wikipedia.java:118)
        at modules.WebLookupModule.lookup(WebLookupModule.java:40)
        at modules.Wikipedia.lookup(Wikipedia.java:60)
        at modules.Wikipedia.wikipediaLink(Wikipedia.java:37)

```

**Comment by mrozekma** [comment]
Essentially the same as #70. Maybe I should fix bugs at a slightly faster rate
